### ISSUE TITLE
XSI: Result stack is copied not modeling stack

### ISSUE THREAD

**Issue by probiner** [heimlich1024/OD_CopyPasteExternal#16]
When copying a mesh in XSI the result stack is the one copied. While it's fine it would be better that it was the modeling stack state that was copied. Otherwise the shape keys, if applied, won't make much sense.

**Comment by nunoalexconceicao** [comment]
Either possibilities make sense, with a slight difference, if doing the modeling stack instead of the result, I will only be able to copy the base mesh , while if I copy the result, I can have both options, to either copy the modeling by mutting all the operators I dont want applied or to be able to copy a mesh with deformations applied. So I think the result is the most logical workflow-wise.

**Comment by probiner** [comment]
I see, yeah, one can do "Disable from here" in a stack operator. Houdini script requires you select the node you want to be the exported one, so I wonder if in XSI say, you select the object only it copies the result, bu if you select an operator the script makes disable from here, copy, enable from here. this way the user won't have to do it, it's included in the tool.

Example:

Application.DeactivateAbove("sphere.polymsh.extrudenormalop", True)

OD Copy Paste.

Application.DeactivateAbove("sphere.polymsh.extrudenormalop", "")



Something like this could actually be interesting for applications with a operators/nodes, like Houdini is working atm.

Cheers

**Comment by nunoalexconceicao** [comment]
I dont really agree with that logic, houdini has a node based funcionality where its easy to see what each node is adding to the flow, its kind of expected to work that way, while in XSI, Maya and Max its operator stack logic, and in those apps the user is used to enable disable the operators they need, and see the result. I dont see why in xsi it should be different than maya or max in that regard since its pretty easy for the common user to just enable/disable the operators they want. 
I can include the possibilty of the script to detect if the user selects an operator then to disable from that point, but the user wont see it and I'm not sure it will be obvious or if most users will even care for that feature.
